import { useState } from 'react';
import { useSegments } from '@/contexts/SegmentsContext';
import { useData } from '@/contexts/DataContext';
import { SegmentCard } from '@/components/segments/SegmentCard';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Plus, Search, Sparkles, Users, TrendingUp } from 'lucide-react';
import { MetricCard } from '@/components/common/MetricCard';
import { Segment } from '@/types';
import { useNavigate } from 'react-router-dom';
import { toast } from '@/hooks/use-toast';

export default function Segments() {
  const navigate = useNavigate();
  const { segments, deleteSegment } = useSegments();
  const { customers, DISPLAY_MULTIPLIER } = useData();
  const [searchQuery, setSearchQuery] = useState('');

  const filteredSegments = segments.filter(segment =>
    segment.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
    segment.description.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const totalSegmentCustomers = segments.reduce((sum, s) => sum + s.customerCount, 0);
  const autoSegments = segments.filter(s => s.isAutoGenerated).length;

  const handleUseInCampaign = (segment: Segment) => {
    navigate('/campaigns', { state: { preselectedSegment: segment } });
    toast({
      title: "Campaign wizard opened",
      description: `Pre-filled with ${segment.name} segment`,
    });
  };

  const handleExport = (segment: Segment) => {
    toast({
      title: "Export started",
      description: `Exporting ${segment.customerCount} customers...`,
    });
  };

  const handleDelete = (segment: Segment) => {
    deleteSegment(segment.id);
    toast({
      title: "Segment deleted",
      description: `${segment.name} has been removed`,
    });
  };

  return (
    <div className="container mx-auto p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-foreground">Customer Segments</h1>
          <p className="text-muted-foreground mt-1">
            Manage and target customer groups at scale
          </p>
        </div>
        <Button onClick={() => navigate('/segment-builder')}>
          <Plus className="h-4 w-4 mr-2" />
          Create Segment
        </Button>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <MetricCard
          title="Total Segments"
          value={segments.length.toString()}
          icon={Users}
          iconColor="text-primary"
          borderColor="border-t-primary"
        />
        <MetricCard
          title="Total Customers"
          value={customers.length.toLocaleString()}
          icon={Users}
          iconColor="text-blue-500"
        />
        <MetricCard
          title="In Segments"
          value={totalSegmentCustomers.toLocaleString()}
          icon={TrendingUp}
          iconColor="text-success"
        />
        <MetricCard
          title="AI Segments"
          value={autoSegments.toString()}
          icon={Sparkles}
          iconColor="text-purple-500"
        />
      </div>

      {/* Search */}
      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
        <Input
          placeholder="Search segments..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="pl-9"
        />
      </div>

      {/* Segments Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {filteredSegments.map(segment => (
          <SegmentCard
            key={segment.id}
            segment={segment}
            onUseInCampaign={handleUseInCampaign}
            onExport={handleExport}
            onDelete={!segment.isAutoGenerated ? handleDelete : undefined}
          />
        ))}
      </div>

      {filteredSegments.length === 0 && (
        <div className="text-center py-12">
          <Users className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
          <h3 className="text-lg font-semibold text-foreground mb-2">No segments found</h3>
          <p className="text-muted-foreground mb-4">
            {searchQuery ? 'Try a different search term' : 'Create your first segment to get started'}
          </p>
          <Button onClick={() => navigate('/segment-builder')}>
            <Plus className="h-4 w-4 mr-2" />
            Create Segment
          </Button>
        </div>
      )}
    </div>
  );
}
