import { useState } from 'react';
import { useSegments } from '@/contexts/SegmentsContext';
import { useData } from '@/contexts/DataContext';
import { SegmentCard } from '@/components/segments/SegmentCard';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Plus, Search, Sparkles, Users, TrendingUp, Filter, X } from 'lucide-react';
import { MetricCard } from '@/components/common/MetricCard';
import { Segment } from '@/types';
import { useNavigate } from 'react-router-dom';
import { toast } from '@/hooks/use-toast';
import { Card } from '@/components/ui/card';
import { RangeFilter, NumericRange } from '@/components/common/RangeFilter';

export default function Segments() {
  const navigate = useNavigate();
  const { segments, deleteSegment } = useSegments();
  const { customers, DISPLAY_MULTIPLIER } = useData();
  const [searchQuery, setSearchQuery] = useState('');
  const [typeFilter, setTypeFilter] = useState('all');
  const [sentimentFilter, setSentimentFilter] = useState('all');
  const [sizeRange, setSizeRange] = useState<NumericRange>({ min: undefined, max: undefined });

  const filteredSegments = segments.filter(segment => {
    const matchesSearch = segment.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      segment.description.toLowerCase().includes(searchQuery.toLowerCase());

    const matchesType = typeFilter === 'all' ||
      (typeFilter === 'auto' && segment.isAutoGenerated) ||
      (typeFilter === 'manual' && !segment.isAutoGenerated);

    const matchesSentiment = sentimentFilter === 'all' || segment.sentimentBucket === sentimentFilter;

    const matchesSize = (sizeRange.min === undefined || segment.customerCount >= sizeRange.min) &&
                        (sizeRange.max === undefined || segment.customerCount <= sizeRange.max);

    return matchesSearch && matchesType && matchesSentiment && matchesSize;
  });

  const hasActiveFilters = typeFilter !== 'all' || sentimentFilter !== 'all' ||
    sizeRange.min !== undefined || sizeRange.max !== undefined;

  const clearFilters = () => {
    setTypeFilter('all');
    setSentimentFilter('all');
    setSizeRange({ min: undefined, max: undefined });
  };

  const totalSegmentCustomers = segments.reduce((sum, s) => sum + s.customerCount, 0);
  const autoSegments = segments.filter(s => s.isAutoGenerated).length;

  const handleUseInCampaign = (segment: Segment) => {
    navigate('/campaigns', { state: { preselectedSegment: segment } });
    toast({
      title: "Campaign wizard opened",
      description: `Pre-filled with ${segment.name} segment`,
    });
  };

  const handleExport = (segment: Segment) => {
    toast({
      title: "Export started",
      description: `Exporting ${segment.customerCount} customers...`,
    });
  };

  const handleDelete = (segment: Segment) => {
    deleteSegment(segment.id);
    toast({
      title: "Segment deleted",
      description: `${segment.name} has been removed`,
    });
  };

  return (
    <div className="container mx-auto p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-foreground">Customer Segments</h1>
          <p className="text-muted-foreground mt-1">
            Manage and target customer groups at scale
          </p>
        </div>
        <Button onClick={() => navigate('/segment-builder')}>
          <Plus className="h-4 w-4 mr-2" />
          Create Segment
        </Button>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <MetricCard
          title="Total Segments"
          value={segments.length.toString()}
          icon={Users}
          iconColor="text-primary"
          borderColor="border-t-primary"
        />
        <MetricCard
          title="Total Customers"
          value={customers.length.toLocaleString()}
          icon={Users}
          iconColor="text-blue-500"
        />
        <MetricCard
          title="In Segments"
          value={totalSegmentCustomers.toLocaleString()}
          icon={TrendingUp}
          iconColor="text-success"
        />
        <MetricCard
          title="AI Segments"
          value={autoSegments.toString()}
          icon={Sparkles}
          iconColor="text-purple-500"
        />
      </div>

      {/* Filters */}
      <Card className="p-4">
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Filter className="h-4 w-4" />
              <span>Filters</span>
              {hasActiveFilters && (
                <span className="text-xs bg-primary text-primary-foreground px-2 py-0.5 rounded-full">
                  Active
                </span>
              )}
            </div>
            {hasActiveFilters && (
              <Button variant="ghost" size="sm" onClick={clearFilters}>
                <X className="h-4 w-4 mr-1" />
                Clear All
              </Button>
            )}
          </div>

          <div className="flex flex-col md:flex-row gap-3 flex-wrap">
            <div className="relative flex-1 min-w-[250px]">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search segments..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-9"
              />
            </div>

            <Select value={typeFilter} onValueChange={setTypeFilter}>
              <SelectTrigger className="w-[160px]">
                <SelectValue placeholder="Segment Type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Types</SelectItem>
                <SelectItem value="auto">Auto-Generated</SelectItem>
                <SelectItem value="manual">Manual</SelectItem>
              </SelectContent>
            </Select>

            <Select value={sentimentFilter} onValueChange={setSentimentFilter}>
              <SelectTrigger className="w-[200px]">
                <SelectValue placeholder="Sentiment Bucket" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Sentiments</SelectItem>
                <SelectItem value="champions">Champions</SelectItem>
                <SelectItem value="loyal">Loyal Customers</SelectItem>
                <SelectItem value="potential">Potential Loyalists</SelectItem>
                <SelectItem value="new">New Customers</SelectItem>
                <SelectItem value="promising">Promising</SelectItem>
                <SelectItem value="need-attention">Need Attention</SelectItem>
                <SelectItem value="about-to-sleep">About to Sleep</SelectItem>
                <SelectItem value="at-risk">At Risk</SelectItem>
                <SelectItem value="cant-lose">Can't Lose Them</SelectItem>
                <SelectItem value="hibernating">Hibernating</SelectItem>
                <SelectItem value="lost">Lost</SelectItem>
              </SelectContent>
            </Select>

            <RangeFilter
              value={sizeRange}
              onChange={setSizeRange}
              label="Segment Size"
              min={0}
              max={100000}
              step={100}
            />
          </div>

          <div className="text-sm text-muted-foreground">
            Showing {filteredSegments.length} of {segments.length} segments
          </div>
        </div>
      </Card>

      {/* Segments Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {filteredSegments.map(segment => (
          <SegmentCard
            key={segment.id}
            segment={segment}
            onUseInCampaign={handleUseInCampaign}
            onExport={handleExport}
            onDelete={!segment.isAutoGenerated ? handleDelete : undefined}
          />
        ))}
      </div>

      {filteredSegments.length === 0 && (
        <div className="text-center py-12">
          <Users className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
          <h3 className="text-lg font-semibold text-foreground mb-2">No segments found</h3>
          <p className="text-muted-foreground mb-4">
            {searchQuery ? 'Try a different search term' : 'Create your first segment to get started'}
          </p>
          <Button onClick={() => navigate('/segment-builder')}>
            <Plus className="h-4 w-4 mr-2" />
            Create Segment
          </Button>
        </div>
      )}
    </div>
  );
}
