import { Campaign } from '@/types/campaign';

export const sampleCampaigns: Campaign[] = [
  {
    id: '1',
    name: 'Welcome Email Series',
    type: 'Email',
    status: 'active',
    targetAudience: 'New Customers',
    lifecycleTarget: 'new',
    segmentSize: 1250,
    subject: 'Welcome to our family! 🎉',
    message: 'Thank you for joining us. Here\'s everything you need to get started.',
    ctaText: 'Get Started',
    ctaLink: 'https://app.example.com/onboarding',
    launchDate: '2025-01-15',
    endDate: '2025-12-31',
    sent: 1250,
    delivered: 1238,
    opened: 856,
    clicked: 428,
    converted: 171,
    revenue: 85500,
    roi: 4.2,
    isWinBackCampaign: false,
    reactivationCount: 0,
    goal: 'onboarding',
    priority: 'high',
    budget: 2500
  },
  {
    id: '2',
    name: 'Win-Back Campaign - Churned Users',
    type: 'Email',
    status: 'active',
    targetAudience: 'Churned Customers',
    lifecycleTarget: 'churned',
    segmentSize: 3200,
    subject: 'We miss you! Come back with 30% off',
    message: 'It\'s been a while. We\'ve made some exciting improvements and want you back.',
    ctaText: 'Claim Your Discount',
    ctaLink: 'https://app.example.com/winback-offer',
    launchDate: '2025-02-01',
    endDate: '2025-03-31',
    sent: 3200,
    delivered: 3152,
    opened: 1261,
    clicked: 504,
    converted: 288,
    revenue: 144000,
    roi: 3.6,
    isWinBackCampaign: true,
    reactivationCount: 288,
    goal: 'win-back',
    priority: 'urgent',
    budget: 8000
  },
  {
    id: '3',
    name: 'Product Launch - Premium Features',
    type: 'Push',
    status: 'scheduled',
    targetAudience: 'Active & Loyal Customers',
    lifecycleTarget: 'loyal',
    segmentSize: 5400,
    subject: 'Exclusive early access to Premium features',
    message: 'Be among the first to experience our new premium tier.',
    ctaText: 'Explore Premium',
    ctaLink: 'https://app.example.com/premium',
    launchDate: '2025-03-15',
    endDate: '2025-04-15',
    sent: 0,
    delivered: 0,
    opened: 0,
    clicked: 0,
    converted: 0,
    revenue: 0,
    roi: 0,
    isWinBackCampaign: false,
    reactivationCount: 0,
    goal: 'upsell',
    priority: 'high',
    budget: 12000
  },
  {
    id: '4',
    name: 'At-Risk Customer Engagement',
    type: 'SMS',
    status: 'active',
    targetAudience: 'At-Risk Customers',
    lifecycleTarget: 'at-risk',
    segmentSize: 2100,
    subject: 'Quick check-in',
    message: 'Hey! We noticed you haven\'t been around. Need help with anything?',
    ctaText: 'Let\'s Talk',
    ctaLink: 'https://app.example.com/support',
    launchDate: '2025-02-10',
    endDate: '2025-04-30',
    sent: 2100,
    delivered: 2079,
    opened: 1456,
    clicked: 583,
    converted: 189,
    revenue: 56700,
    roi: 2.8,
    isWinBackCampaign: false,
    reactivationCount: 0,
    goal: 'retention',
    priority: 'high',
    budget: 4200
  },
  {
    id: '5',
    name: 'Cross-Sell Campaign - Add-ons',
    type: 'WhatsApp',
    status: 'completed',
    targetAudience: 'Active Customers',
    lifecycleTarget: 'active',
    segmentSize: 4500,
    subject: 'Enhance your experience',
    message: 'Based on your usage, you might love these premium add-ons.',
    ctaText: 'View Add-ons',
    ctaLink: 'https://app.example.com/addons',
    launchDate: '2025-01-01',
    endDate: '2025-01-31',
    sent: 4500,
    delivered: 4455,
    opened: 3119,
    clicked: 1248,
    converted: 562,
    revenue: 168600,
    roi: 5.6,
    isWinBackCampaign: false,
    reactivationCount: 0,
    goal: 'cross-sell',
    priority: 'medium',
    budget: 6750
  },
  {
    id: '6',
    name: 'Reactivation Nurture Series',
    type: 'Email',
    status: 'active',
    targetAudience: 'Recently Reactivated',
    lifecycleTarget: 'reactivated',
    segmentSize: 890,
    subject: 'Welcome back! Here\'s what\'s new',
    message: 'Great to have you back! Check out everything we\'ve improved since you were last here.',
    ctaText: 'See What\'s New',
    ctaLink: 'https://app.example.com/whats-new',
    launchDate: '2025-02-15',
    endDate: '2025-05-31',
    sent: 890,
    delivered: 881,
    opened: 617,
    clicked: 309,
    converted: 139,
    revenue: 41700,
    roi: 3.9,
    isWinBackCampaign: false,
    reactivationCount: 0,
    goal: 'reactivation-nurture',
    priority: 'medium',
    budget: 1780
  },
  {
    id: '7',
    name: 'Seasonal Promotion - Spring Sale',
    type: 'Email',
    status: 'paused',
    targetAudience: 'All Active Users',
    lifecycleTarget: 'all',
    segmentSize: 12500,
    subject: 'Spring into savings - 25% off everything',
    message: 'Our biggest sale of the season is here. Limited time only!',
    ctaText: 'Shop Now',
    ctaLink: 'https://app.example.com/spring-sale',
    launchDate: '2025-03-01',
    endDate: '2025-03-31',
    sent: 6200,
    delivered: 6138,
    opened: 3069,
    clicked: 1228,
    converted: 491,
    revenue: 147300,
    roi: 4.7,
    isWinBackCampaign: false,
    reactivationCount: 0,
    goal: 'activation',
    priority: 'medium',
    budget: 9375
  }
];
