import { Segment } from '@/types';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { formatCurrency } from '@/utils/formatters';
import { Users, TrendingUp, TrendingDown, Minus, Sparkles, Target, MoreVertical } from 'lucide-react';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

interface SegmentCardProps {
  segment: Segment;
  onClick?: (segment: Segment) => void;
  onUseInCampaign?: (segment: Segment) => void;
  onEdit?: (segment: Segment) => void;
  onDelete?: (segment: Segment) => void;
  onExport?: (segment: Segment) => void;
}

export const SegmentCard = ({ segment, onClick, onUseInCampaign, onEdit, onDelete, onExport }: SegmentCardProps) => {
  const getTrendIcon = () => {
    switch (segment.metrics.trend) {
      case 'up': return <TrendingUp className="h-4 w-4 text-success" />;
      case 'down': return <TrendingDown className="h-4 w-4 text-destructive" />;
      default: return <Minus className="h-4 w-4 text-muted-foreground" />;
    }
  };

  const getTypeColor = () => {
    switch (segment.type) {
      case 'auto': return 'bg-primary/10 text-primary border-primary/30';
      case 'sentiment': return 'bg-purple-500/10 text-purple-600 border-purple-500/30';
      case 'lifecycle': return 'bg-blue-500/10 text-blue-600 border-blue-500/30';
      default: return 'bg-muted text-muted-foreground border-border';
    }
  };

  return (
    <Card
      className="p-5 hover:shadow-md transition-shadow cursor-pointer"
      onClick={() => onClick?.(segment)}
    >
      <div className="flex items-start justify-between mb-3">
        <div className="flex-1">
          <div className="flex items-center gap-2 mb-1">
            <h3 className="font-semibold text-foreground">{segment.name}</h3>
            {segment.isAutoGenerated && (
              <Sparkles className="h-3.5 w-3.5 text-primary" />
            )}
          </div>
          <p className="text-sm text-muted-foreground">{segment.description}</p>
        </div>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button
              variant="ghost"
              size="sm"
              className="h-8 w-8 p-0"
              onClick={(e) => e.stopPropagation()}
            >
              <MoreVertical className="h-4 w-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            {onUseInCampaign && (
              <DropdownMenuItem onClick={(e) => { e.stopPropagation(); onUseInCampaign(segment); }}>
                <Target className="h-4 w-4 mr-2" />
                Use in Campaign
              </DropdownMenuItem>
            )}
            {onEdit && !segment.isAutoGenerated && (
              <DropdownMenuItem onClick={(e) => { e.stopPropagation(); onEdit(segment); }}>
                Edit Segment
              </DropdownMenuItem>
            )}
            {onExport && (
              <DropdownMenuItem onClick={(e) => { e.stopPropagation(); onExport(segment); }}>
                Export Customers
              </DropdownMenuItem>
            )}
            {onDelete && !segment.isAutoGenerated && (
              <DropdownMenuItem
                onClick={(e) => { e.stopPropagation(); onDelete(segment); }}
                className="text-destructive"
              >
                Delete Segment
              </DropdownMenuItem>
            )}
          </DropdownMenuContent>
        </DropdownMenu>
      </div>

      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <span className={`text-xs px-2 py-1 rounded-full border font-medium ${getTypeColor()}`}>
            {segment.type.toUpperCase()}
          </span>
          <span className="text-xs text-muted-foreground">
            Updated {new Date(segment.lastUpdated).toLocaleDateString()}
          </span>
        </div>

        <div className="grid grid-cols-2 gap-3">
          <div className="space-y-1">
            <div className="flex items-center gap-1 text-muted-foreground">
              <Users className="h-3.5 w-3.5" />
              <span className="text-xs">Customers</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-xl font-bold text-foreground">
                {segment.customerCount.toLocaleString()}
              </span>
              {getTrendIcon()}
            </div>
          </div>

          <div className="space-y-1">
            <span className="text-xs text-muted-foreground">Avg LTV</span>
            <p className="text-xl font-bold text-foreground">
              {formatCurrency(segment.metrics.avgLTV)}
            </p>
          </div>
        </div>

        <div className="pt-2 border-t">
          <div className="flex items-center justify-between text-xs">
            <span className="text-muted-foreground">Total LTV:</span>
            <span className="font-semibold text-foreground">
              {formatCurrency(segment.metrics.totalLTV)}
            </span>
          </div>
          <div className="flex items-center justify-between text-xs mt-1">
            <span className="text-muted-foreground">Churn Rate:</span>
            <span className={`font-semibold ${
              segment.metrics.churnRate > 0.3 ? 'text-destructive' : 'text-success'
            }`}>
              {(segment.metrics.churnRate * 100).toFixed(1)}%
            </span>
          </div>
        </div>
      </div>
    </Card>
  );
};
